### ISSUE TITLE
Add description for exponential interpolation

### ISSUE THREAD

**Issue by lossius** [j45ch/sptdf04_issues#52]
so that we have support for Zirkonium authored works

**Comment by lossius** [comment]
Assigned to Chikashi

**Comment by chikashimiyama** [comment]
I think the right name for the function is not exponential function but power function

https://en.wikipedia.org/wiki/Exponential_function
https://en.wikipedia.org/wiki/Power_function
http://chargerisk.com/science/power-expo.php

because x is variable but power value (c) is constant;
Thus, I renamed it with "power" and added explanation.
